Module7 task1
htmlacademy-ecmascript/1290757-cinemaddict-13 pull request #10
Opened 2021-01-10 14:47 UTC by Argtum

2021-01-11 17:10 UTC, AxemaFr requested changes

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +    }
default?

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +    this._sortingView.setSortTypeChangeHandler(this._handleSortTypeChange);
Не очень понятно, зачем пихать null в поле, если строкой ниже в него и так, и так записывается новое значение.

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +  _clearFilmList({resetRenderedTaskCount = false, resetSortType = false} = {}) {
Красиво описал аргументы. Мне нравится.

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +    this._filmPresenter = new Map();
почему поле filmPresenter (название в единственном числе) содержит в себе мапу?

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +    }
Опционально - можно красиво сделать через тернарник.

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +    }
default?

2021-01-11 17:10 UTC, AxemaFr commented on src/presenter/page-main-content.js
> +        break;
2 блока с очень похожей логикой. Может вынести куда-то? (DRY)

2021-01-11 17:10 UTC, AxemaFr commented on src/utils/stats.js
> +};
Что-то не то :)

countCompleted**_Task_**InDateRange

2021-01-11 17:10 UTC, AxemaFr commented on src/view/filter.js
> +  }
Снова очень сильно похожие конструкции. Вынесем?

2021-01-11 17:10 UTC, AxemaFr commented on src/view/popup.js
> +    }
см коммент выше

2021-01-12 20:57 UTC, Argtum commented on src/presenter/film.js
>      remove(this._popupView);
В моём случае отображение popup рендерится при его открытии, в начальный момент времени его нет и при обновлении страницы может произойти удаление несуществующих обработчиков.

2021-01-15 17:35 UTC, merged